/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.idea.completion;

import org.xtext.example.mydsl.idea.completion.AbstractMyDslCompletionContributor;

@SuppressWarnings("all")
public class MyDslCompletionContributor extends AbstractMyDslCompletionContributor {
  public MyDslCompletionContributor() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe constructor MyDslCompletionContributor(AbstractXtextLanguage) refers to the missing type AbstractXtextLanguage");
  }
  
  public MyDslCompletionContributor(final /* AbstractXtextLanguage */Object lang) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(AbstractXtextLanguage) is undefined");
  }
}
