/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.idea.facet;

/* @State(, ) */@SuppressWarnings("all")
public class MyDslFacetConfiguration /* implements AbstractFacetConfiguration, PersistentStateComponent<GeneratorConfigurationState>  */{
}
